syntax = "proto3";

package namespace.stdlib;

option go_package = "namespacelabs.dev/internal/public/gen/proto/namespace/stdlib";

// Represents a time series of data, associating multiple string-keyed data
// points to each timestamp.
//
// Each data point N has a timestamp stored in timestamps[N].
// Data associated with that timestamp is then stored in:
// - doubles[key].values[N] if the data is represented as a double
// - integers[key].values[N] if the data is represented as a int64
// - strings[key].values[N] if the data is represented as a string
//
// The API that returns a TimeSeries describes which keys will be present.
message TimeSeries {
    // timestamps are represented as the number of nanoseconds elapsed since
    // January 1, 1970 UTC.
    repeated int64        timestamps = 1;
    map<string, Doubles>  doubles    = 2;
    map<string, Integers> integers   = 3;
    map<string, Strings>  strings    = 4;

    message Doubles {
        repeated double values = 1;
    }

    message Integers {
        repeated int64 values = 1;
    }

    message Strings {
        repeated string values = 1;
    }
}
